# Generated by Django 5.2.1 on 2025-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
